---
version: '3'

dotenv: ['.env']

tasks:
  # New task to upload all coverage reports to Coveralls
  coverage:upload:
    desc: Upload both Host and Firmware coverage to Coveralls
    cmds:
      - coveralls report lcov.info coverage.xml -n -r {{ .COVERALLS_REPO_TOKEN }}
    silent: true

  deps:
    desc: "Install dependencies"
    cmds:
      - sudo apt install gcovr
      - rustup component add llvm-tools-preview
      - cargo install cargo-llvm-cov

  default:
    desc: List available tasks
    cmds:
      - task --list

  setup:
    desc: Install dependencies and setup environment
    cmds:
      - echo "Setting up environment..."
      # Add setup commands here, e.g., cargo install, pio install

  build:
    desc: Build both Host and Firmware
    deps: [host:build, firmware:build]

  check:
    desc: Run all checks (format, lint, test)
    deps: [host:check, firmware:check]

  test:ci:
    desc: Run tests using the CI profile
    dir: host
    cmds:
      - task: fmt:check
      - task: lint
      - cargo test --profile ci
      - task: clippy
      - task: firmware:test
      - task: firmware:check

  clippy:
    desc: Run cargo clippy
    dir: host
    cmds:
      - cargo clippy --workspace --all-targets --all-features -- -D warnings

  lint:
    desc: Lint code with clippy
    dir: host
    cmds:
      - cargo clippy -- -D warnings

  fmt:check:
    desc: Check code formatting with rustfmt
    dir: host
    cmds:
      - cargo fmt -- --check
      
  host:build:
    desc: Build the Host (Rust)
    dir: host
    cmds:
      - cargo build

  host:build:amd64:
    desc: Build for AMD64 (x86_64)
    dir: host
    cmds:
      - cross build --release --target x86_64-unknown-linux-gnu

  host:build:arm64:
    desc: Build for ARM64 (aarch64)
    dir: host
    cmds:
      - cross build --release --target aarch64-unknown-linux-gnu

  host:build:armv7:
    desc: Build for ARMv7
    dir: host
    cmds:
      - cross build --release --target armv7-unknown-linux-gnueabihf

  host:build:armv6:
    desc: Build for ARMv6
    dir: host
    cmds:
      - cross build --release --target arm-unknown-linux-gnueabihf

  host:build:all:
    desc: Build for all supported architectures
    cmds:
      - task: host:build:amd64
      - task: host:build:arm64
      - task: host:build:armv7
      - task: host:build:armv6

  host:run:
    desc: Run the Host (Rust)
    dir: host
    cmds:
      - cargo run -- {{.CLI_ARGS}}

  host:check:
    desc: Check Host code (fmt, clippy, test)
    dir: host
    cmds:
      - cargo fmt --all -- --check
      - cargo clippy -- -D warnings
      - cargo test

  host:coverage:
    desc: Run code coverage for the Host project
    dir: host
    cmds:
      - cargo llvm-cov

  host:coverage:lcov:
    desc: Generate LCOV coverage report for the Host project (for Codecov)
    dir: host
    cmds:
      - cargo llvm-cov --lcov --output-path ../lcov.info

  firmware:build:
    desc: Build the Firmware (PlatformIO)
    dir: firmware
    cmds:
      - pio run -e esp32-c6-geek

  firmware:flash:
    desc: Flash the Firmware (PlatformIO)
    dir: firmware
    cmds:
      - pio run -e esp32-c6-geek -t upload

  firmware:monitor:
    desc: Start Serial Monitor (PlatformIO)
    dir: firmware
    interactive: true
    cmds:
      - pio device monitor

  firmware:check:
    desc: Check Firmware code
    dir: firmware
    cmds:
      - pio check

  firmware:test:
    desc: Run Firmware unit tests (native)
    dir: firmware
    cmds:
      - pio test -e native

  firmware:coverage:
    desc: Run Firmware unit tests and generate coverage report using gcovr
    dir: firmware
    cmds:
      - pio test -e native
      - gcovr -r . --filter include/ --filter src/ --print-summary --exclude ".*/.pio/.*" --gcov-ignore-errors=no_working_dir_found

  firmware:coverage:xml:
    desc: Generate Cobertura XML coverage report for the Firmware
    dir: firmware
    cmds:
      - pio test -e native
      - gcovr -r . --filter include/ --filter src/ --exclude ".*/.pio/.*" --xml-pretty -o ../coverage.xml --gcov-ignore-errors=no_working_dir_found
