---
version: '3'

dotenv: ['.env']

tasks:
  init:
    desc: Initiate the .env file
    preconditions:
      - sh: test -f .env.tmpl
        msg: ".env.tmpl doesn't exist"
    cmds:
      - cp .env.tmpl .env
  encrypt:
    desc: Encrypt files using SOPS
    preconditions:
      - sh: test -f .env
        msg: ".env file doens't exist"
    cmds:
      - sops -e --input-type dotenv --output-type dotenv .env > .env.enc
  decrypt:
    desc: Decrypt files using SOPS
    preconditions:
      - sh: test -f .env.enc
        msg: ".env.enc doesn't exist"
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env
  # New task to upload all coverage reports to Coveralls
  coverage:upload:
    desc: Upload all coverage reports to Coveralls
    cmds:
      - coveralls report lcov.info coverage.xml coverage_sh.xml -n -r {{ .COVERALLS_REPO_TOKEN }}
    silent: true

  coverage:sh:
    desc: Run shell script coverage with kcov
    cmds:
      - bash tests/flash_script_functional.sh
      - echo "Coverage report generated in coverage/index.html"

  coverage:sh:xml:
    desc: Generate Cobertura XML coverage report for shell scripts
    cmds:
      - task: coverage:sh
      - find coverage -name "cobertura.xml" -exec cp {} coverage_sh.xml \;
      - echo "Shell coverage XML generated at coverage_sh.xml"

  deps:
    desc: "Install dependencies"
    cmds:
      - sudo apt install gcovr kcov
      - rustup component add llvm-tools-preview
      - cargo install cargo-llvm-cov

  default:
    desc: List available tasks
    cmds:
      - task --list

  setup:
    desc: Install dependencies and setup environment
    cmds:
      - echo "Setting up environment..."
      # Add setup commands here, e.g., cargo install, pio install

  build:
    desc: Build both Host and Firmware
    deps: [host:build, firmware:build]

  check:
    desc: Run all checks (format, lint, test)
    deps: [host:check, firmware:check]

  test:ci:
    desc: Run tests using the CI profile
    dir: host
    cmds:
      - task: fmt:check
      - task: lint
      - cargo test --profile ci
      - task: clippy
      - task: firmware:test
      - task: firmware:check

  clippy:
    desc: Run cargo clippy
    dir: host
    cmds:
      - cargo clippy --workspace --all-targets --all-features -- -D warnings

  lint:
    desc: Lint code with clippy
    dir: host
    cmds:
      - cargo clippy -- -D warnings

  fmt:check:
    desc: Check code formatting with rustfmt
    dir: host
    cmds:
      - cargo fmt -- --check
      
  host:build:
    desc: Build the Host (Rust)
    dir: host
    cmds:
      - cargo build

  host:build:amd64:
    desc: Build for AMD64 (x86_64)
    dir: host
    cmds:
      - cross build --release --target x86_64-unknown-linux-gnu

  host:build:arm64:
    desc: Build for ARM64 (aarch64)
    dir: host
    cmds:
      - cross build --release --target aarch64-unknown-linux-gnu

  host:build:armv7:
    desc: Build for ARMv7
    dir: host
    cmds:
      - cross build --release --target armv7-unknown-linux-gnueabihf

  host:build:armv6:
    desc: Build for ARMv6
    dir: host
    cmds:
      - cross build --release --target arm-unknown-linux-gnueabihf

  host:build:all:
    desc: Build for all supported architectures
    cmds:
      - task: host:build:amd64
      - task: host:build:arm64
      - task: host:build:armv7
      - task: host:build:armv6

  host:run:
    desc: Run the Host (Rust)
    dir: host
    cmds:
      - cargo run -- {{.CLI_ARGS}}

  host:check:
    desc: Check Host code (fmt, clippy, test)
    dir: host
    cmds:
      - cargo fmt --all -- --check
      - cargo clippy -- -D warnings
      - cargo test

  host:deps:update:
    desc: Update Host dependencies to latest versions
    dir: host
    cmds:
      - cargo update

  host:coverage:
    desc: Run code coverage for the Host project
    dir: host
    cmds:
      - cargo llvm-cov

  host:coverage:lcov:
    desc: Generate LCOV coverage report for the Host project (for Codecov)
    dir: host
    cmds:
      - cargo llvm-cov --lcov --output-path ../lcov.info

  host:docker:build:
    desc: Build the Host agent Docker image
    cmds:
      - docker build -t side-eye-host .

  host:docker:run:
    desc: Run the Host agent Docker image
    cmds:
      - docker run --privileged -v /dev:/dev -v ./side-eye.toml:/etc/side-eye/config.toml side-eye-host

  docker:up:
    desc: Start SideEye using Docker Compose
    cmds:
      - docker compose up -d

  docker:down:
    desc: Stop SideEye using Docker Compose
    cmds:
      - docker compose down

  docker:logs:
    desc: View SideEye logs using Docker Compose
    cmds:
      - docker compose logs -f

  firmware:build:
    desc: Build the Firmware (PlatformIO)
    dir: firmware
    cmds:
      - pio run -e esp32-c6-geek

  firmware:flash:
    desc: Flash the Firmware (PlatformIO)
    dir: firmware
    cmds:
      - pio run -e esp32-c6-geek -t upload

  firmware:flash:script:
    desc: Flash the Firmware (script)
    dir: firmware
    cmds:
      - bash scripts/flash.sh

  firmware:monitor:
    desc: Start Serial Monitor (PlatformIO)
    dir: firmware
    interactive: true
    cmds:
      - pio device monitor

  firmware:check:
    desc: Check Firmware code
    dir: firmware
    cmds:
      - pio check

  firmware:deps:update:
    desc: Update Firmware dependencies to latest versions
    dir: firmware
    cmds:
      - pio pkg update

  firmware:test:
    desc: Run Firmware unit tests (native)
    dir: firmware
    cmds:
      - pio test -e native

  firmware:coverage:
    desc: Run Firmware unit tests and generate coverage report using gcovr
    dir: firmware
    cmds:
      - pio test -e native
      - gcovr -r . --filter include/ --filter src/ --print-summary --exclude ".*/.pio/.*" --gcov-ignore-errors=no_working_dir_found

  firmware:coverage:xml:
    desc: Generate Cobertura XML coverage report for the Firmware
    dir: firmware
    cmds:
      - pio test -e native
      - gcovr -r . --filter include/ --filter src/ --exclude ".*/.pio/.*" --xml-pretty -o ../coverage.xml --gcov-ignore-errors=no_working_dir_found

  test:mqtt:
    desc: Run automated MQTT integration tests
    cmds:
      - sudo docker compose -f tests/mqtt/compose.yaml up -d
      - defer: sudo docker compose -f tests/mqtt/compose.yaml down
      - |
        ./tests/mqtt/.venv/bin/python tests/mqtt/validator.py --test --timeout 10 &
        sleep 2
        sudo docker compose -f tests/mqtt/compose.yaml exec mosquitto mosquitto_pub -h localhost -t "side-eye/test-device/stats" -m '{"version": "1.0.0", "uptime": 100}'
        wait

