#ifndef CATPPUCCIN_COLORS_H
#define CATPPUCCIN_COLORS_H

// Catppuccin Mocha Theme - RGB565 (16-bit)
#define CATPPUCCIN_ROSEWATER 0xF78B
#define CATPPUCCIN_FLAMINGO  0xF669
#define CATPPUCCIN_PINK      0xF61C
#define CATPPUCCIN_MAUVE     0xC53E
#define CATPPUCCIN_RED       0xF12B
#define CATPPUCCIN_MAROON    0xE24B
#define CATPPUCCIN_PEACH     0xF94B
#define CATPPUCCIN_YELLOW    0xF5C5
#define CATPPUCCIN_GREEN     0xA5C8
#define CATPPUCCIN_TEAL      0x936A
#define CATPPUCCIN_SKY       0x86DE
#define CATPPUCCIN_SAPPHIRE  0x727D
#define CATPPUCCIN_BLUE      0x859F
#define CATPPUCCIN_LAVENDER  0xB57F
#define CATPPUCCIN_TEXT      0xB03F
#define CATPPUCCIN_SUBTEXT1  0x9F7F
#define CATPPUCCIN_SUBTEXT0  0x8EBE
#define CATPPUCCIN_OVERLAY2  0x7E0E
#define CATPPUCCIN_OVERLAY1  0x6D3F
#define CATPPUCCIN_OVERLAY0  0x5C99
#define CATPPUCCIN_SURFACE2  0x4B6E
#define CATPPUCCIN_SURFACE1  0x3A4B
#define CATPPUCCIN_SURFACE0  0x29A8
#define CATPPUCCIN_BASE      0x18E5
#define CATPPUCCIN_MANTLE    0x18C4
#define CATPPUCCIN_CRUST     0x1083

#endif // CATPPUCCIN_COLORS_H
